overrides:
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12 <2.0.0'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  ajv@<6.14.0: '>=6.14.0'
  minimatch@<3.1.3: '>=3.1.3'
  minimatch@>=9.0.0 <9.0.6: '>=9.0.6'
